on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - uses: codecov/codecov-action@v5
